development:
 adapter: postgresql
 encoding: unicode
 database: chadder_dev
 host: localhost
 pool: 5
 username: jamesnewman
 password: password

test:
 adapter: postgresql
 encoding: unicode
 database: chadder_test
 host: localhost
 pool: 5
 username: jamesnewman
 password: password