development:
 adapter: postgresql
 encoding: unicode
 database: chadder_dev
 host: localhost
 pool: 5
 username: ENV['DB_USERNAME']
 password: ENV['DB_PASS']

test:
 adapter: postgresql
 encoding: unicode
 database: chadder_test
 host: localhost
 pool: 5
 username: ENV['DB_USERNAME']
 password: ENV['DB_PASS']